/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['index.js']) {
  _$jscoverage['index.js'] = [];
  _$jscoverage['index.js'][2] = 0;
  _$jscoverage['index.js'][3] = 0;
}
_$jscoverage['index.js'][2]++;
exports.getName = (function getName() {
  _$jscoverage['index.js'][3]++;
  return "\u4f60\u597d";
});
_$jscoverage['index.js'].source = ["","exports.getName = function getName() {","  return '&#20320;&#22909;';","};"];
